; This file was auto-generated by drush make and manualy changed
core = 7.x

api = 2

projects[] = "drupal" 

; Modules

projects[] = "block_titlelink"
projects[] = "ctools"
projects[] = "colorbox"
projects[] = "entity"
projects[] = "filefield_paths"
projects[] = "imagecache_actions"
projects[] = "imce"
projects[] = "imce_wysiwyg"
projects[] = "libraries"
projects[] = "link"
projects[] = "menu_block"
projects[] = "menu_expanded"
projects[] = "metatags_quick"
projects[] = "references"
projects[] = "nodereference_url"
projects[] = "page_title"
projects[] = "pathauto"
projects[] = "pathologic"
projects[] = "print"
projects[] = "smtp"
projects[] = "taxonomy_display"
projects[] = "token"
projects[] = "transliteration"
projects[] = "views"
projects[] = "webform"
projects[] = "wysiwyg"
projects[] = "conditional_styles"
projects[] = "crumbs"
projects[] = "file_entity"
projects[] = "media"
projects[] = "media_youtube"
projects[] = "features"

; Pathed modules and special versions

projects[l10n_update][version] = 1.x-dev

projects[less][type] = "module"
projects[less][download][type] = git
projects[less][download][url] = git://github.com/LyudmilaPetrova/less.git


; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[fix_comments][download][type] = ""
; projects[fix_comments][download][url] = ""
; projects[fix_comments][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[map][download][type] = ""
; projects[map][download][url] = ""
; projects[map][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[news][download][type] = ""
; projects[news][download][url] = ""
; projects[news][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[placeholder][download][type] = ""
; projects[placeholder][download][url] = ""
; projects[placeholder][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[printpluspdf][download][type] = ""
; projects[printpluspdf][download][url] = ""
; projects[printpluspdf][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[skin][download][type] = ""
; projects[skin][download][url] = ""
; projects[skin][type] = "module"

; Themes
projects[base3][download][type] = "git"
projects[base3][download][url] = "git://github.com/LyudmilaPetrova/base3.git"
projects[base3][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; ORIGINAL
; libraries[lessphp][download][type] = "get"
; libraries[lessphp][download][url] = "http://leafo.net/lessphp/src/lessphp-0.3.8.tar.gz"
; libraries[lessphp][directory_name] = "lessphp"
; libraries[lessphp][type] = "library"
; WE NEED PATCHED!!!
libraries[lessphp][download][type] = "get"
libraries[lessphp][download][url] = "https://nodeload.github.com/Nodge/lessphp/tarball/master"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"


; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://www.jacklmoore.com/colorbox/colorbox.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = "get"
libraries[tinymce][download][url] = "http://github.com/downloads/tinymce/tinymce/tinymce_3.5.6_jquery.zip"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

