; This file was auto-generated by drush make and manualy changed
core = 7.x

api = 2

; Modules
projects[] = "block_titlelink"
projects[] = "ctools"
projects[] = "colorbox"
projects[] = "entity"
projects[] = "filefield_paths"
projects[] = "imagecache_actions"
projects[] = "imce"
projects[] = "imce_wysiwyg"

projects[] = "less"
projects[] = "libraries"
projects[] = "link"
projects[] = "menu_block"
projects[] = "menu_expanded"
projects[] = "metatags_quick"
projects[] = "references"
projects[] = "nodereference_url"
projects[] = "page_title"
projects[] = "pathauto"
projects[] = "pathologic"
projects[] = "print"
projects[] = "smtp"
projects[] = "taxonomy_display"
projects[] = "token"
projects[] = "transliteration"
projects[] = "views"
projects[] = "webform"
projects[] = "wysiwyg"
projects[] = "conditional_styles"
projects[] = "crumbs"
projects[] = "file_entity"
projects[] = "media"
projects[] = "media_youtube"
projects[] = "features"

projects[l10n_update][version] = 1.x-dev




; Themes
; projects[] = "twitter_bootstrap"
; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[fix][download][type] = ""
; projects[fix][download][url] = ""
; projects[fix][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[fix_comments][download][type] = ""
; projects[fix_comments][download][url] = ""
; projects[fix_comments][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[map][download][type] = ""
; projects[map][download][url] = ""
; projects[map][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[news][download][type] = ""
; projects[news][download][url] = ""
; projects[news][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[placeholder][download][type] = ""
; projects[placeholder][download][url] = ""
; projects[placeholder][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[printpluspdf][download][type] = ""
; projects[printpluspdf][download][url] = ""
; projects[printpluspdf][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[skin][download][type] = ""
; projects[skin][download][url] = ""
; projects[skin][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[base2][download][type] = ""
; projects[base2][download][url] = ""
; projects[base2][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[dao][download][type] = ""
; projects[dao][download][url] = ""
; projects[dao][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = "get"
libraries[lessphp][download][url] = "http://leafo.net/lessphp/src/lessphp-0.3.8.tar.gz"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://www.jacklmoore.com/colorbox/colorbox.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = "get"
libraries[tinymce][download][url] = "http://github.com/downloads/tinymce/tinymce/tinymce_3.5.6_jquery.zip"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

