; This file was auto-generated by drush make and manualy changed
core = 7.x

api = 2

projects[] = "drupal" 

; Modules

projects[] = "block_titlelink"
projects[] = "ctools"
projects[] = "colorbox"
projects[] = "entity"
projects[] = "filefield_paths"
projects[] = "imagecache_actions"
projects[] = "imce"
projects[] = "imce_wysiwyg"
projects[] = "libraries"
projects[] = "link"
projects[] = "menu_block"
projects[] = "menu_expanded"
projects[] = "metatags_quick"
projects[] = "references"
projects[] = "nodereference_url"
projects[] = "page_title"
projects[] = "pathauto"
projects[] = "pathologic"
projects[] = "print"
projects[] = "smtp"
projects[] = "taxonomy_display"
projects[] = "token"
projects[] = "transliteration"
projects[] = "views"
projects[] = "webform"
projects[] = "wysiwyg"
projects[] = "conditional_styles"
projects[] = "crumbs"
projects[] = "file_entity"
projects[] = "media"
projects[] = "media_youtube"
projects[] = "features"

; Pathed contributed modules and special versions

projects[l10n_update][version] = 1.x-dev

projects[less][type] = "module"
projects[less][download][type] = git
projects[less][download][url] = git://github.com/LyudmilaPetrova/less.git

; Libraries

; WE NEED PATCHED LESSPHP
libraries[lessphp][download][type] = "get"
libraries[lessphp][download][url] = "https://nodeload.github.com/Nodge/lessphp/tarball/master"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://www.jacklmoore.com/colorbox/colorbox.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[tinymce][download][type] = "get"
libraries[tinymce][download][url] = "http://github.com/downloads/tinymce/tinymce/tinymce_3.5.6_jquery.zip"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Custom modules

projects[fix][subdir] = "custom"
projects[fix][download][type] = "git"
projects[fix][download][url] = "git://github.com/LyudmilaPetrova/fix.git"
projects[fix][type] = "module"

projects[fix_comments][subdir] = "custom"
projects[fix_comments][download][type] = "git"
projects[fix_comments][download][url] = "git://github.com/LyudmilaPetrova/fix_comments.git"
projects[fix_comments][type] = "module"

projects[fix_search_form][subdir] = "custom"
projects[fix_search_form][download][type] = "git"
projects[fix_search_form][download][url] = "git://github.com/LyudmilaPetrova/fix_search_form.git"
projects[fix_search_form][type] = "module"

projects[placeholder][subdir] = "custom"
projects[placeholder][download][type] = "git"
projects[placeholder][download][url] = "git://github.com/LyudmilaPetrova/placeholder.git"
projects[placeholder][type] = "module"

projects[domain_theme_switcher][subdir] = "custom"
projects[domain_theme_switcher][download][type] = "git"
projects[domain_theme_switcher][download][url] = "git://github.com/LyudmilaPetrova/domain_theme_switcher.git"
projects[domain_theme_switcher][type] = "module"

projects[yasearch][subdir] = "custom"
projects[yasearch][download][type] = "git"
projects[yasearch][download][url] = "git://github.com/LyudmilaPetrova/yasearch.git"
projects[yasearch][type] = "module"

projects[ie_warning][subdir] = "custom"
projects[ie_warning][download][type] = "git"
projects[ie_warning][download][url] = "git://github.com/LyudmilaPetrova/ie_warning.git"
projects[ie_warning][type] = "module"

; Custom theme

projects[base3][download][type] = "git"
projects[base3][download][url] = "git://github.com/LyudmilaPetrova/base3.git"
projects[base3][type] = "theme"

; Guber installation profile
; TODO
